### ISSUE TITLE
Project setting issue (camel case)

### ISSUE THREAD

**Issue by ghost** [react-native-admob/admob#3]
Hello,

I try to install your librairie but I found an error during the "pod install" part, I saw this line :   
`Installing RNAdMob (0.1.6)`

But after when I launch "run-ios", I saw that, 
`error Could not find the following native modules: RNAdmob. Did you forget to run "pod install" ?`

The difference between the two is just the "M" in upper or lower case

**Comment by wjaykim** [comment]
Could you run `pod deintegrate & pod install`? I cannot find why this issue happened.

**Comment by ghost** [comment]
I guess it's a problem with my project setup.

At the beginning I managed the ads with this lib :  https://github.com/sbugert/react-native-admob

I started to transfer ad management to Firebase-admob before realizing that it didn't support "NativeAds".
So I find myself with 2 obsolete libraries in my project and I will have to get all that clean and especially find an "up to date" library for "NativeAds"

Does your library have the possibility to work with the config "pod 'Google-Mobile-Ads-SDK', '~> 7.69.0'" ? (Maybe on an old release version)  So as not to have to update all the ad config at once  (big big project with many ads )

**Comment by wjaykim** [comment]
I think it will work on version 7.69.0 since beta apis related to version 8.0 are introduced in 7.67.0, but I doesn't guarantee it.

I believe NativeAds library you are saying is https://github.com/ammarahm-ed/react-native-admob-native-ads. I am contributing to the ammarahm-ed's library as well, and there we almost done migrating SDK from 7.69.0 to 8.+., but not released new version yet.

Also I think in the future native ads components will be added in my library.

**Comment by wjaykim** [comment]
Closing this issue as you found solution.
